
language: php

addons:
  apt:
    packages:
      - parallel

matrix:
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7
      env: TYPO3_VERSION=^7.6
    - php: 7
      env: TYPO3_VERSION=^8
    - php: 7
      env: TYPO3_VERSION=dev-master
  allow_failures:
    - env: TYPO3_VERSION=dev-master

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      composer set-version $TRAVIS_TAG
      # If this fails, we forgot to update version numbers before tagging the release
      test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";
    fi
  - composer require typo3/cms=$TYPO3_VERSION
  - export TYPO3_PATH_WEB="$PWD/.Build/Web"

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Executing PHP code sniffer"; 
    .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=PSR2 Classes/

after_script:
  - >
    echo;
    echo "Everything done";
